os: windows
language: sh
env:
  - PYTHON_VERSION=3.4.4
    PYTHON_HOME='C:\Python34'
    MSBUILD='C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe'
    PATH="$PYTHON_HOME:$PYTHON_HOME\Scripts:$PATH"

cache:
  directories:
    - C:\ProgramData\Microsoft\VisualStudio\Package

install:
# install python
  - choco install python --version $PYTHON_VERSION
  - curl --retry 5 https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - pip install -r InstallerGUI/requirements.txt
# install visual studio
  - choco install visualstudio2017community
  - choco install visualstudio2017-workload-managedgame --package-parameters "--no-includeRecommended"
  - choco install visualstudio2017-workload-manageddesktopbuildtools --package-parameters "--no-includeRecommended --add Microsoft.VisualStudio.Component.TestTools.BuildTools --add Microsoft.Net.Component.4.TargetingPack"

script:
  - "$MSBUILD" 140-speedrun-timer.sln /target:Installer /p:Configuration=Release
  - cd InstallerGUI && ./build.cmd

deploy:
  provider: releases
  api_key:
    secure: NpkJj+mXEFHO1v3e725HgkpGb28hvdsIAP9NMNkFnzwQqfB07OJlPJki2OaG/Pl1dOlCkZc4fD49sofAjIR3y+1r+rvHno0494E9u98lO0pKaV23sRYzBQr689G9QA+NQmKSh6yHSCJtftsGQLilfk5EPdiwEp5Bib+P76WFiMnrfdjE21eQdDElPBqJCsS4a58nyxuYOT53TU6Z2ShuND03NWjyZ+d+Jt2pTet1WGcSJ13h9JoHNJTNrMuyLjUE47TnCeiTEe5Ni8Ue2PeN5Q4lXImeI/+tBIrD6NOu5U8R/iOQM2oXmF5E8SM83uNCrG0J/A7u2oLKNyw3rv5eMobqXBASkWX6FPd1g3TzYSxkw1N4AvbqbtOpOhN00ebRPInze9ttRrv1E7pucXdcqIR8LUFyf5glX6rhZvl6tijwxyYj3qpu2xeb6wgf68w0/59xjNJupDkrj4hpnrBCD+zbfVgG88j9yp3Ec0JQdy7S1IvLJ5p/F3WZQ2u684vazGPdJsRm3sEsj5te+rAXadwcBf6sTmFgWqvIUwDoV1cbdhsM8+OWlwEl0AWCKGbhBcrHbUJPCYlrxQtmfKyW8WrXkccH8v3ImD+4H9SKGWw6M+ZDe317TtCa7j7M+zpA6VGRubhGiRfLuKnaUFA198qrqVMZgalZhvycI05E3lg=
  file: $TRAVIS_BUILD_DIR/InstallerGUI/dist/speedrun-timer-installer.exe
  on:
    repo: Dalet/140-speedrun-timer
    tags: true
    all_branches: true
  draft: true
  name: $TRAVIS_TAG
